from sqlalchemy import Boolean, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.enums import JobSeekerVerificationStatus
from app.models.mixins import TimestampMixin


class JobSeekerProfile(TimestampMixin, Base):
    __tablename__ = "job_seeker_profiles"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False)
    phone: Mapped[str | None] = mapped_column(String(30), nullable=True)
    github_url: Mapped[str | None] = mapped_column(String(255), nullable=True)
    resume_pdf_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    about: Mapped[str | None] = mapped_column(Text, nullable=True)
    verification_status: Mapped[str] = mapped_column(String(30), default=JobSeekerVerificationStatus.PENDING.value, nullable=False)
    certificates_public: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    education: Mapped[str | None] = mapped_column(String(160), nullable=True)
    degree: Mapped[str | None] = mapped_column(String(160), nullable=True)
    college: Mapped[str | None] = mapped_column(String(180), nullable=True)
    passing_year: Mapped[int | None] = mapped_column(Integer, nullable=True)
    cgpa_or_percentage: Mapped[str | None] = mapped_column(String(40), nullable=True)
    skills: Mapped[str | None] = mapped_column(Text, nullable=True)
    experience_level: Mapped[str | None] = mapped_column(String(40), nullable=True)
    preferred_location: Mapped[str | None] = mapped_column(String(160), nullable=True)
    preferred_job_type: Mapped[str | None] = mapped_column(String(40), nullable=True)
    job_seeker_category: Mapped[str | None] = mapped_column(String(40), nullable=True)
    college_name: Mapped[str | None] = mapped_column(String(180), nullable=True)
    university_name: Mapped[str | None] = mapped_column(String(180), nullable=True)
    course_name: Mapped[str | None] = mapped_column(String(160), nullable=True)
    degree_name: Mapped[str | None] = mapped_column(String(160), nullable=True)
    department_or_branch: Mapped[str | None] = mapped_column(String(160), nullable=True)
    current_year_or_semester: Mapped[str | None] = mapped_column(String(80), nullable=True)
    expected_passing_year: Mapped[int | None] = mapped_column(Integer, nullable=True)
    college_location: Mapped[str | None] = mapped_column(String(160), nullable=True)
    student_id_number: Mapped[str | None] = mapped_column(String(120), nullable=True)
    internship_interest: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    preferred_internship_roles: Mapped[str | None] = mapped_column(Text, nullable=True)
    highest_degree: Mapped[str | None] = mapped_column(String(160), nullable=True)
    graduation_year: Mapped[int | None] = mapped_column(Integer, nullable=True)
    specialization_or_branch: Mapped[str | None] = mapped_column(String(160), nullable=True)
    fresher_skills: Mapped[str | None] = mapped_column(Text, nullable=True)
    certifications: Mapped[str | None] = mapped_column(Text, nullable=True)
    project_links: Mapped[str | None] = mapped_column(Text, nullable=True)
    internship_experience: Mapped[str | None] = mapped_column(Text, nullable=True)
    preferred_job_roles: Mapped[str | None] = mapped_column(Text, nullable=True)
    total_experience_years: Mapped[float | None] = mapped_column(Float, nullable=True)
    current_or_last_company: Mapped[str | None] = mapped_column(String(180), nullable=True)
    current_or_last_role: Mapped[str | None] = mapped_column(String(160), nullable=True)
    employment_type: Mapped[str | None] = mapped_column(String(80), nullable=True)
    notice_period: Mapped[str | None] = mapped_column(String(80), nullable=True)
    previous_companies: Mapped[str | None] = mapped_column(Text, nullable=True)
    role_history: Mapped[str | None] = mapped_column(Text, nullable=True)
    key_responsibilities: Mapped[str | None] = mapped_column(Text, nullable=True)
    tools_technologies: Mapped[str | None] = mapped_column(Text, nullable=True)
    achievements: Mapped[str | None] = mapped_column(Text, nullable=True)
    preferred_next_roles: Mapped[str | None] = mapped_column(Text, nullable=True)
    education_visibility: Mapped[str] = mapped_column(String(30), default="PUBLIC", nullable=False)
    experience_visibility: Mapped[str] = mapped_column(String(30), default="PUBLIC", nullable=False)
    recommendation_visibility: Mapped[str] = mapped_column(String(30), default="PRIVATE", nullable=False)
    reference_visibility: Mapped[str] = mapped_column(String(30), default="PRIVATE", nullable=False)
    certificate_visibility: Mapped[str] = mapped_column(String(30), default="PUBLIC", nullable=False)
    has_accessibility_needs: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    accessibility_needs: Mapped[str | None] = mapped_column(Text, nullable=True)
    accessibility_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    accessibility_visibility: Mapped[str] = mapped_column(String(30), default="PRIVATE", nullable=False)
    student_verification_status: Mapped[str] = mapped_column(String(40), default="STUDENT_UNVERIFIED", nullable=False)
    graduation_verification_status: Mapped[str] = mapped_column(String(40), default="GRADUATION_UNVERIFIED", nullable=False)
    experience_verification_status: Mapped[str] = mapped_column(String(40), default="EXPERIENCE_UNVERIFIED", nullable=False)

    user = relationship("User", back_populates="job_seeker_profile")
    recommendations = relationship("JobSeekerRecommendation", back_populates="profile", cascade="all, delete-orphan")
    references = relationship("JobSeekerReference", back_populates="profile", cascade="all, delete-orphan")
